[main]
prefix = "!"
description = "Description"
owner_id = 123
timezone = "Europe/Amsterdam"

[api_keys]
discord_token = "token"
spotify_client = "spotify_client"
spotify_token = "spotify_token"

[voice_chat]
category_id = 123
create_voice_channel_id = 123
waiting_room_voice_channel_id = 123
voice_channel_owner_role_id = 123

[role]
role_divider_id = 123

[clock]
channel_id = 123

[song]
playlist_id = "playlist_id"
channel_id = 123

[yoeri]
guild_id = 123
user_id = 123